version: '2'
services:
  parity:
    image: parity/parity:v1.9.7
    command: --no-ui --no-discovery --jsonrpc-interface all --ws-interface all --ws-port 8546 --ws-origins all -d /root/.parity
    restart: unless-stopped
    volumes:
      - /root/.parity:/root/.parity
    expose:
      - 8545
      - 8546

  contract_observer:
    image: forkdelta/backend-replacement
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PROVIDER_URL: ${HTTP_PROVIDER_URL}
      WS_PROVIDER_URL: ${WS_PROVIDER_URL}
    links:
      - postgres
      - redis
      - parity
    command: >
      python3 -m app.services.contract_observer

  etherdelta_observer:
    image: forkdelta/backend-replacement
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PROVIDER_URL: ${HTTP_PROVIDER_URL}
    links:
      - postgres
      - redis
      - parity
    command: >
      python3 -m app.services.etherdelta_observer

  huey_consumer:
    image: forkdelta/backend-replacement
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PROVIDER_URL: ${HTTP_PROVIDER_URL}
    links:
      - postgres
      - redis
      - parity
    command: >
      huey_consumer.py app.services.huey_consumer.huey -w ${HUEY_CONCURRENCY} -k greenlet

  ticker:
    image: forkdelta/backend-replacement
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PROVIDER_URL: ${HTTP_PROVIDER_URL}
    links:
      - postgres
      - parity
    command: >
      python3 -m app.services.ticker

  websocket_server:
    image: forkdelta/backend-replacement
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HTTP_PROVIDER_URL: ${HTTP_PROVIDER_URL}
    links:
      - postgres
      - redis
      - parity
    command: >
      python3 -m app.services.websocket_server

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 18080:8080
